### ISSUE TITLE
想请教下，这个版本是否已经修复兼容问题

### ISSUE THREAD

**Issue by children117cl** [wuhan005/vue-datetime#2]
我用 vue-datetime 时，部分手机（例如华为）组件中的日期生成不出数据，可能是报错了；

然后我找到了你的代码，看到你提交的，是修改了 capitalize 函数；

想向你请教一下：
1. 你修改的这一版是为了修复同样的问题吗？
2. 出现这个错误，有找到是什么原因吗？

**Comment by wuhan005** [comment]
该代码是今年年初的时候写的，记不太清了。。。

当时是为了修复在某些移动端下，该日历组件无法正常显示的问题。（具体机器型号和浏览器不记得了）
定位到问题是`capitalize`这个函数中的`toUpperCase`未定义。
这是功能为将给定字符串开头字母转大写的函数，我这边直接很暴力的直接将这个函数的输入直接 return 了。之后日历控件便可以正常使用了。😁

**Comment by children117cl** [comment]
明白了，感谢讲解~今早客户

**Comment by children117cl** [comment]
明白了，感谢讲解~
今早客户也反馈问题已经修复了~
